config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, {only: [:new, :create, :edit, :update, :destroy]}
  before_action :article_find, {only: [:show, :edit, :destroy, :update]}
  before_action :user_find, {only: [:show, :edit, :destroy, :update]}

  def index 
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to root_path
    flash[:notice] = "You created article."
  end

  def show
    
  end

  def edit
    flash[:notice] = "You edited article."
  end

  def update
    flash[:notice] = "You updated article."
  end

  def destroy
    flash[:notice] = "You destroyed article."
  end

  private
    def article_params
      params.require(:article).permit(:title, :content, :user_id)
    end

    def article_find
      @article = Article.find(params[:id])
    end

    def user_find
      @user = User.find_by(id: @article.user_id)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   @user = User.new
  # end

  # POST /resource
  # def create
  #   @user = User.find(user_params)
  #   @user.save
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/application/_header.html.erb
<header>
	<div class="header-left">Tatsuya <span><%= link_to "Blog", root_path %></span></div>
	<div class="header-right">
		<ul>
			<li><%= link_to "トップ", root_path %></li>
			<% if user_signed_in? %>
			<li><%= link_to "新規投稿", new_article_path %></li>			
			<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
			<% else %>
			<li><%= link_to "新規登録", new_user_registration_path %></li>
			<li><%= link_to "ログイン", new_user_session_path %></li>			
			<% end%>			
		</ul>
	</div>
</header>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<%= image_tag 'header.jpeg', :size => '1400x400' %>

<div id="article-list">
	<% @articles.each do |article| %>
		<div>
			<div id="article-title"><%= link_to "#{article.title}", article_path(article) %></div>
			<div id="article-created_at"><%= article.created_at %></div>	
		</div>
	<% end %>
</div>

app/views/articles/new.html.erb
<div class="container">
	<%= form_with(model: @article, local: true) do |form| %>

		<div class="field">
			<%= form.label :title, "タイトル" %>
			<%= form.text_field :title, placeholder: "タイトルを入力してね" %>
		</div>

		<div class="field">
			<%= form.label :content, "記事内容" %>
			<%= form.text_area :content, placeholder: "内容を入力してね" %>
		</div>

		<div>
			<%= form.hidden_field :user_id, value: current_user.id %>
		</div>

		<div class="actions">
			<%= form.submit %>
		</div>
	<% end %>
</div>

app/views/articles/show.html.erb
<div class="show-container">
	<div class="top-container">
		<div class="show-top">
			<p>
				作成日-
				<%= @article.created_at %>
			</p>
			<p>
				作成者-
				<%= @user.email %>
			</p>
		</div>
		<div class="show-title">
			タイトル-
			<%= @article.title %>
		</div>
	</div>
	<div class="foot-container">
		<div class="show-content">
			内容は
			~<span><%= @article.content %></span>~
			です。
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= render 'header' %>
    <div class="container">
        <%= yield %>
    </div>
    <%= render 'footer' %>
  </body>
</html>